CREATE TYPE "NotificationType" AS ENUM (
  'GENERAL',
  'AUTO_ORDER',
  'LOW_STOCK',
  'OUT_OF_STOCK',
  'PREP_URGENT',
  'CUSTOMER_FEEDBACK',
  'INGREDIENT_OVERPRICE',
  'INGREDIENT_PRICE_INCREASE',
  'PUBLIC_HOLIDAY',
  'SPECIAL_MENU'
);

ALTER TABLE "notifications" ADD COLUMN "type" "NotificationType" NOT NULL DEFAULT 'GENERAL';
